### PR TITLE
WEB-2394 family locator sdk bridge methods

### LINKED ISSUE #246: Family Locator web view bridge methods
This issue groups the Family Locator SDK bridge methods required in the shared spec https://telefonicacorp.sharepoint.com/:w:/r/sites/Colabora_TCX/_layouts/15/Doc.aspx?sourcedoc=%7BD524FA49-9937-4D20-958A-7055D67B65DB%7D&file=Shared%20Spec%20%25u2013%20OBVIVO-3177%20-%20Family%20locator.docx&nav=eyJjIjoxMjA3NDU5NjUzfQ&action=default&mobileredirect=true

## Enable/configure SDK

**Message type**: `SETUP_LOCATOR_SDK_CONFIG`

**Originator**: Web

**Min app version**: TBD

## Description

Used during service activation. Receives a config object and calls `sdk.setConfig(config)`. After setting the configuration, the flow expects the app to call `sdk.start()` and check for errors (missing permissions, etc...)

The configuration is a JSON like the following one:

```json
{ 
  "id": "a5a70879-febb-4833-a99c-f0deb6061f56", 
  "requestId": "req_config_01", 
  "timestamp": 1764612254353, 
  "data": { 
    "license": "47545a0c-ebbe-4501-ba45-73443928a037", 
    "sdkVersion": "2.0.1", 
    "osPlatform": "android", 
    "api": { 
      "token": "eyJhbGciOiJIUzI1.....", 
      "certUrl": "https://locator-api-stage-13376dba-1ef4-41e2-ab1b-ea98248b0b3d.datamobpro.com/cert", 
      "tokenUrl": "https://locator-api-stage-13376dba-1ef4-41e2-ab1b-ea98248b0b3d.datamobpro.com/token", 
      "scopesUrl": "https://locator-api-stage-13376dba-1ef4-41e2-ab1b-ea98248b0b3d.datamobpro.com/scopes", 
      "configUrl": "https://locator-api-stage-13376dba-1ef4-41e2-ab1b-ea98248b0b3d.datamobpro.com/config", 
      "groupsUrl": "https://locator-api-stage-13376dba-1ef4-41e2-ab1b-ea98248b0b3d.datamobpro.com/groups", 
      "featuresUrl": "https://locator-api-stage-13376dba-1ef4-41e2-ab1b-ea98248b0b3d.datamobpro.com/features", 
      "geofencesUrl": "https://locator-api-stage-13376dba-1ef4-41e2-ab1b-ea98248b0b3d.datamobpro.com/geofences" 
    }, 
    "mqtt": { 
      "clientId": "LIC-1234567890-sdk", 
      "broker": "vivo-locator-mqtt.datamobpro.com", 
      "port": "8883", 
      "username": "LIC-1234567890" 
    }, 
    "process": { 
      "offlineRetentionDays": 30, 
      "retryPolicy": { 
        "maxRetries": 10, 
        "baseDelayMs": 200, 
        "backoffFactor": 1.5 
      }, 
      "foregroundServiceNotification": { 
        "title": "Localização ativa", 
        "message": "O aplicativo está coletando localização em segundo plano." 
      } 
    }, 
    "battery": { 
      "events": [ 
        { 
          "name": "battery_low_warning", 
          "min": 0, 
          "max": 15, 
          "interval": 600000, 
          "charging": false, 
          "powerMode": [ 
            "normal", 
            "power_saver" 
          ] 
        }, 
        { 
          "name": "battery_charging_optimization", 
          "min": 80, 
          "max": 100, 
          "interval": 900000, 
          "charging": true, 
          "powerMode": [ 
            "normal" 
          ] 
        } 
      ] 
    }, 
    "motion": { 
      "sensitivity": 10 
    }, 
    "collect": { 
      "collectIntervalMillis": 180000, 
      "sendIntervalMillis": 3600000, 
      "minDisplacementMeters": 50, 
      "maxTravelDistanceMeters": 2000, 
      "highAccuracy": true, 
      "maxBatchSize": 100 
    }, 
    "revision": 1, 
    "createdAt": 1710087520010, 
    "updatedAt": null 
  } 
} 
```

In the bridge definition we can let the config be an arbitrary JSON

## Payload definition

**Request Payload**

```ts
{
  config: LocatorSdkConfigObject; // passed to sdk.setConfig
}
```

Example:

```json
{
  "type": "ENABLE_LOCATOR_SDK_CONFIG",
  "id": "id-enable-locator-sdk-config",
  "payload": {
    "config": { /* config object like the example above */ }
  }
}
```

**Response Payload**  
No payload required.

## Possible error cases

The spec expects two different errors, `LocatorSDKMissingPermissionsException` and `LocatorSDKNoConfigSetException`

401 → `LocatorSDKMissingPermissionsException`. This error will be returned when the SDK detects that there are pending permissions to be requested
402 → `LocatorSDKNoConfigSetException`. This error will be returned when the config can't be set for any other reason.
500 → Internal Error: If an error occurred processing the message

---

## Check if the SDK is configured (getState)

**Message type**: `GET_LOCATOR_SDK_STATE`

**Originator**: Web

**Min app version**: TBD

## Description

Used to determine if the user already has the service active on the device. Wrapper for the SDK method `getState`. 

## Payload definition

**Request Payload**  
No payload required.

Example:

```json
{
  "type": "GET_LOCATOR_SDK_STATE",
  "id": "id-get-locator-sdk-state"
}
```

**Response Payload**

```ts
{
  state: string;         // raw SDK state
}
```

Example:

```json
{
  "type": "GET_LOCATOR_SDK_STATE",
  "id": "id-get-locator-sdk-state",
  "payload": {
    "state": "collecting",
  }
}
```

## Possible error cases

- 500 → Internal Error: If an error occurred processing the message

---

## Start real-time location sharing & start/stop SOS mode (setSdkMode)

**Message type**: `SET_LOCATOR_SDK_MODE`

**Originator**: Web

**Min app version**: TBD

## Description

Used when user starts viewing the map / activates SOS. Wrapper for `setSdkMode(mode)`

- `setSdkMode("observed")` → start real-time location sharing
- `setSdkMode("sos")` → start SOS + real-time sharing
- `setSdkMode("default")` → return to default mode (disable real-time); used when cancelling SOS

## Payload definition

**Request Payload**

```ts
{
  mode: string; //"default" | "observed" | "sos"
}
```

Example:

```json
{
  "type": "SET_LOCATOR_SDK_MODE",
  "id": "id-set-locator-sdk-mode",
  "payload": { "mode": "observed" }
}
```

**Response Payload**  
No payload required.

## Possible error cases

- 500 → Internal Error: If an error occurred processing the message

---

## Obtaining JWT token (getJwtToken)

**Message type**: `GET_LOCATOR_JWT_TOKEN`

**Originator**: Web

**Min app version**: TBD

## Description

Wrapper for `getJwtToken`. Returns the JWT that will be used to authenticate the map communication between the Framework Brasil frontend and the Datamob backend.

## Payload definition

**Request Payload**  
No payload required.

Example:

```json
{
  "type": "GET_LOCATOR_JWT_TOKEN",
  "id": "id-get-locator-jwt-token"
}
```

**Response Payload**

```ts
{
  token: string;
}
```

Example:

```json
{
  "type": "GET_LOCATOR_JWT_TOKEN",
  "id": "id-get-locator-jwt-token",
  "payload": { "token": "jwt-token" }
}
```

## Possible error cases

- 500 → Internal Error: If an error occurred processing the message

---

## Obtaining pending permissions (pendingPermissions)

**Message type**: `GET_LOCATOR_PENDING_PERMISSIONS`

**Originator**: Web

**Min app version**: TBD

## Description

Used when user starts viewing the map. Wrapper for `pendingPermissions`. Returns which required user permissions are still pending.

## Payload definition

**Request Payload**  
No payload required.

Example:

```json
{
  "type": "GET_LOCATOR_PENDING_PERMISSIONS",
  "id": "id-get-locator-pending-permissions"
}
```

**Response Payload**

```ts
{
  permissions: string[];
}
```

Example:

```json
{
  "type": "GET_LOCATOR_PENDING_PERMISSIONS",
  "id": "id-get-locator-pending-permissions",
  "payload": {
    "permissions": ["location_in_use", "location_background"]
  }
}
```

## Differences between iOS/Android

The identifier for the permissions are different per platform

Android
```kotlin
LOCATION_FINE = "location_fine",
LOCATION_COARSE = "location_coarse",
LOCATION_BACKGROUND = "location_background",
ACTIVITY_RECOGNITION = "activity_recognition",
BODY_SENSORS = "body_sensors",
BATTERY_OPTIMIZATION = "battery_optimization",
FOREGROUND_SERVICE = "foreground_service"
FOREGROUND_SERVICE_LOCATION = "foreground_service_location"
ACCESS_NETWORK_STATE = "access_network_state"
```
iOS
```swift
NSLocationWhenInUseUsageDescription = "location_in_use"
NSLocationAlwaysAndWhenInUseUsageDescription = "location_background"
NSMotionUsageDescription = "motion_usage"
NSFallDetectionUsageDescription = "fall_detection"
```

## Possible error cases

- 500 → Internal Error: If an error occurred processing the message

---

## Obtaining SDK version (getVersion)

**Message type**: `GET_LOCATOR_SDK_VERSION`

**Originator**: Web

**Min app version**: TBD

## Description

Will be used for logging/analytics. Wrapper for `getVersion`.

## Payload definition

**Request Payload**  
No payload required.

Example:

```json
{
  "type": "GET_LOCATOR_SDK_VERSION",
  "id": "id-get-locator-sdk-version"
}
```

**Response Payload**

```ts
{
  version: string;
}
```

Example:

```json
{
  "type": "GET_LOCATOR_SDK_VERSION",
  "id": "id-get-locator-sdk-version",
  "payload": { "version": "2.0.1" }
}
```

## Possible error cases

- 500 → Internal Error: If an error occurred processing the message

---

## Obtaining SDK session (getSession)

**Message type**: `GET_LOCATOR_SDK_SESSION`

**Originator**: Web

**Min app version**: TBD

## Description

Can be used for logging/analytics. Wrapper for `getSession`.

## Payload definition

**Request Payload**  
No payload required.

Example:

```json
{
  "type": "GET_LOCATOR_SDK_SESSION",
  "id": "id-get-locator-sdk-session"
}
```

**Response Payload**

```ts
{
  session: {
    id: string;
    startAt: number; // Int64
    endAt: number | null; // Int64 | null
  };
}
```

Example:

```json
{
  "type": "GET_LOCATOR_SDK_SESSION",
  "id": "id-get-locator-sdk-session",
  "payload": {
    "session": {
      "id": "session-id",
      "startAt": 1710087520010,
      "endAt": null
    }
  }
}
```

## Possible error cases

- 500 → Internal Error: If an error occurred processing the message

---

## Obtaining SDK mode (getSdkMode)

**Message type**: `GET_LOCATOR_SDK_MODE`

**Originator**: Web

**Min app version**: TBD

## Description

Used when user starts viewing the map. Wrapper for `getSdkMode`.

## Payload definition

**Request Payload**  
No payload required.

Example:

```json
{
  "type": "GET_LOCATOR_SDK_MODE",
  "id": "id-get-locator-sdk-mode"
}
```

**Response Payload**

```ts
{
  mode: "default" | "observed" | "sos" | string;
}
```

Example:

```json
{
  "type": "GET_LOCATOR_SDK_MODE",
  "id": "id-get-locator-sdk-mode",
  "payload": { "mode": "observed" }
}
```

## Possible error cases

- 500 → Internal Error: If an error occurred processing the message

---

## Obtaining config (getConfig)

**Message type**: `GET_LOCATOR_SDK_CONFIG`

**Originator**: Web

**Min app version**: TBD

## Description

Used when user starts viewing the map. Wrapper for `getConfig`. Returns current SDK config in JSON format

## Payload definition

**Request Payload**  
No payload required.

Example:

```json
{
  "type": "GET_LOCATOR_SDK_CONFIG",
  "id": "id-get-locator-sdk-config"
}
```

**Response Payload**

```ts
{
  config: LocatorSdkConfigObject | null;
}
```

Example:

```json
{
  "type": "GET_LOCATOR_SDK_CONFIG",
  "id": "id-get-locator-sdk-config",
  "payload": { "config": null }
}
```

## Possible error cases

- 500 → Internal Error: If an error occurred processing the message

### PR DESCRIPTION
**Pull request by atabel**
closes #246

### CODE REVIEW

File: src/family-locator.ts [hunk 1]
```diff
@@ -0,0 +1,54 @@
+import {postMessageToNativeApp} from './post-message';
+
+// Family Locator SDK webview bridge methods.
+// https://telefonicacorp.sharepoint.com/:w:/r/sites/Colabora_TCX/_layouts/15/Doc.aspx?sourcedoc=%7BD524FA49-9937-4D20-958A-7055D67B65DB%7D&file=Shared%20Spec%20%25u2013%20OBVIVO-3177%20-%20Family%20locator.docx&nav=eyJjIjoxMjA3NDU5NjUzfQ&action=default&mobileredirect=true
+
+export type LocatorSdkMode = 'default' | 'observed' | 'sos';
+export type LocatorSdkConfig = Record<string, unknown>;
```
Comment (atabel) [inline src/family-locator.ts]: Is this lose type enough or can we define a more strict type here?

**Review by DevPabloGarcia — APPROVED** [review]
Thanks
